### ISSUE TITLE
pricing broken

### ISSUE THREAD

**Issue by Ali1** [Ali1/imcsand#13]
alawi the pricing page looked very bad. it seems related to a change u made. I've reverse some of the changes by taking out the "a" see https://github.com/Ali1/imcsand/commit/d5fd625ee22282a52dda764512f396b0c15e6ba8

it is better, but still looks strange now

**Comment by alimoshen** [comment]
Can you test it when you get a chance?

**Comment by Ali1** [comment]
just to clarify:

.category-procedures li a span.text { = doesnt work
+.category-procedures li span.text { = works

**Comment by Ali1** [comment]
looks good habibi
