### ISSUE TITLE
admin extremely slow because of ACF

### ISSUE THREAD

**Issue by Ali1** [Ali1/imcsand#17]
Salam

The admin is running extremely slow. I noticed the custom fields plugin needed an update but it doesnt update as it cannot connect to server or something. I realised that disabling it makes everything go faster. I think it's related to wordpress trying to fetch the update information with every admin page load. Do you have any ideas how to stop just this plugin from fetching for updates?

**Comment by alimoshen** [comment]
Sorted ;) 
I've also added the license key and have updated the plugin

**Comment by Ali1** [comment]
habibi the license key means it wont be a problem in the future?

Thanks

**Comment by alimoshen** [comment]
Yes it's a lifetime license key so should be fine.

**Comment by Ali1** [comment]
shokran
