### ISSUE TITLE
fontawesome twice?

### ISSUE THREAD

**Issue by Ali1** [Ali1/imcsand#18]
habibi i see a lot of fontawesome things in style-base but its already on a separate font.css file.

**Comment by alimoshen** [comment]
Did you include the font.css? Because the style-base should have all the css files embedded in one file and not separated. Do you prefer separate files?

**Comment by Ali1** [comment]
Nope I dont think I did. It even has a scss file. Merging everything is fine habibi as long as it's not minified :)

So I've taken out fonts.css then.

Thanks
