### ISSUE TITLE
underline hyperlinks

### ISSUE THREAD

**Issue by Ali1** [Ali1/imcsand#2]
or a blue colour. just something to look more like links as inline links are a bit disguised at the moment.

**Comment by alimoshen** [comment]
Styled the link in the css, but it's not showing on the front end, would you need to switch on the dev mode again?

**Comment by Ali1** [comment]
i reverted your changes to style as the underlining was showing up everywhere even in the sidebar menu, pricing table was broken, and another change i made at the bottom (floating). you can see exactly whats going on here:
https://github.com/Ali1/imcsand/commit/16a20dd45df49bb8571737e97d492219472a243b

**Comment by Ali1** [comment]
also see #13

**Comment by alimoshen** [comment]
Done now, can you test it?
