### ISSUE TITLE
something wrong with images

### ISSUE THREAD

**Issue by Ali1** [Ali1/imcsand#20]
![image](https://cloud.githubusercontent.com/assets/218558/6992443/4aa4e0bc-dac6-11e4-9b7d-7a0f77480f82.png)

Alawi the paragraph text is now looking strange. This happens because the size of the image+margin is not going small enough and so the div is being expanded. Do you mind checking this out?

Thank you

**Comment by alimoshen** [comment]
Should be sorted now.

**Comment by Ali1** [comment]
Habibi are you sure? I'm looking at the adult page on my phone and same
thing. But could be style cache issue so I can check it out later again
