### ISSUE TITLE
blog

### ISSUE THREAD

**Issue by Ali1** [Ali1/imcsand#4]
not really an issue as you haven't worked on it yet, but thought it might be good for you to have a list of things.
https://www.circumcision-london.co.uk/blog/
https://www.circumcision-london.co.uk/welcome-to-the-imc-circumcision-london-blog/

**Comment by Ali1** [comment]
alawi i've made a custom field tickbox to show the blog widgets. when you go to widgets, the blog widgets are in a different place so we can put the search, categories etc. in there

**Comment by alimoshen** [comment]
Allawi, for some strange reason the /blog/ page isn't loading the blog template, but when I create a new page it does work (https://www.circumcision-london.co.uk/test-page/)

Sorry to be a pain but can you enable the dev again? I can't access it anymore to style the sidebar

**Comment by Ali1** [comment]
Done habibi. Btw it last for 3 hours

On Saturday, 28 March 2015, alimoshen <notifications@github.com> wrote:

> Assigned #4 <https://github.com/Ali1/imcsand/issues/4> to @Ali1
> <https://github.com/Ali1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ali1/imcsand/issues/4#event-267646966>.
>


-- 
Sent from my iPhone

**Comment by alimoshen** [comment]
Really strange but I've been trying to upload a CSS for a while now and it's not updating on the site :S

**Comment by Ali1** [comment]
Probably 3 hours is up. I'll do it again habibi

On Saturday, 28 March 2015, alimoshen <notifications@github.com> wrote:

> Really strange but I've been trying to upload a CSS for a while now and
> it's not updating on the site :S
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ali1/imcsand/issues/4#issuecomment-87289082>.
>


-- 
Sent from my iPhone

**Comment by Ali1** [comment]
Hmm it's on but I've done it again. Try now?

On Saturday, 28 March 2015, alimoshen <notifications@github.com> wrote:

> Really strange but I've been trying to upload a CSS for a while now and
> it's not updating on the site :S
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ali1/imcsand/issues/4#issuecomment-87289082>.
>


-- 
Sent from my iPhone

**Comment by alimoshen** [comment]
Great it's working now :) 
I've styled the sidebar, the only thing left is the search form, is it okay if this one is hardcoded instead of a widget? https://www.circumcision-london.co.uk/test-page/

**Comment by Ali1** [comment]
That's absolutely fine as I can always use HTML as a widget.

Thanks for the hard work so far

On Saturday, 28 March 2015, alimoshen <notifications@github.com> wrote:

> Great it's working now :)
> I've styled the sidebar, the only thing left is the search form, is it
> okay if this one is hardcoded instead of a widget?
> https://www.circumcision-london.co.uk/test-page/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ali1/imcsand/issues/4#issuecomment-87290841>.
>


-- 
Sent from my iPhone

**Comment by alimoshen** [comment]
Should be sorted now.

**Comment by Ali1** [comment]
looks great
