### ISSUE TITLE
console errors: i think it's the css import files

### ISSUE THREAD

**Issue by Ali1** [Ali1/imcsand#6]
Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.circumcision-london.co.uk/wp-content/themes/imc/skew.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.circumcision-london.co.uk/wp-content/themes/imc/hinge.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.circumcision-london.co.uk/wp-content/themes/imc/bounce.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.circumcision-london.co.uk/wp-content/themes/imc/zoom.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.circumcision-london.co.uk/wp-content/themes/imc/speed.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.circumcision-london.co.uk/wp-content/themes/imc/space.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.circumcision-london.co.uk/wp-content/themes/imc/slide.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.circumcision-london.co.uk/wp-content/themes/imc/scale.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.circumcision-london.co.uk/wp-content/themes/imc/flip.css Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.circumcision-london.co.uk/wp-content/themes/imc/rotate.css

**Comment by alimoshen** [comment]
Should be sorted now
